trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  openCoverFileName: 'coverage.opencover.xml'
  coberturaFileName: 'coverage.cobertura.xml'  
  sourceFolder: 'src/MeerkatUpdater/'
  sourceCoreFolder : '$(sourceFolder)MeerkatUpdater.Core/'
  sourceTestFolder: '$(sourceFolder)MeerkatUpdater.Core.Test/'  

steps:


- task: UseDotNet@2
  continueOnError: false
  displayName: Use dotnet 3
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
    workingDirectory: '$(sourceFolder)'

- task: DotNetCoreCLI@2
  continueOnError: false
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'
    workingDirectory: '$(sourceFolder)'

- task: DotNetCoreCLI@2
  continueOnError: false
  displayName: Testing
  inputs:
    command: 'test'
    arguments: '--no-build'
    workingDirectory: '$(sourceFolder)'