trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  openCoverFileName: 'coverage.opencover.xml'
  coberturaFileName: 'coverage.cobertura.xml'  
  sourceFolder: 'src/MeerkatUpdater/'
  sourceCoreFolder : '$(sourceFolder)MeerkatUpdater.Core/'
  sourceTestFolder: '$(sourceFolder)MeerkatUpdater.Core.Test/'  
  #MSBUILDSINGLELOADCONTEXT: 1 #This environment is to solve the temporary issue on SpecFlow 3.1.x that can't build by using dotnet build

steps:
- task: UseDotNet@2
  continueOnError: false
  displayName: Use dotnet 3
  inputs:
    packageType: 'sdk'
    version: '3.1.100'

# - task: SonarCloudPrepare@1
#   displayName: Configuring SonarCloud
#   inputs:
#     SonarCloud: 'SonarCloudConnection'
#     organization: 'afborgesdev-github'
#     scannerMode: 'MSBuild'
#     projectKey: 'afborgesDev_MeerkatUpdater'
#     projectName: 'MeerkatUpdater'
#     extraProperties: |
#       sonar.exclusions=**/obj/**,**/*.dll
#       sonar.branch.name=$(Build.SourceBranchName)
#       sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/TestResults/Coverage/$(openCoverFileName)
#       sonar.cs.vstest.reportsPaths=$(Build.SourcesDirectory)/TestResults/Report/*.trx

- task: Bash@3
  displayName: 'Building'
  continueOnError: false
  inputs:
    workingDirectory: '$(sourceCoreFolder)'
    script: 'dotnet build - c $(buildConfiguration)'

- task: Bash@3
  displayName: 'Runing tests'
  #env:
  #  MSBUILDSINGLELOADCONTEXT: 1
  continueOnError: false
  timeoutInMinutes: 5
  inputs:
    workingDirectory: '$(sourceTestFolder)'
    targetType: 'inline'
    script: 'dotnet test MeerkatUpdater.Core.Test.csproj --no-build --logger trx'
#     arguments: '--no-restore'# --logger trx /p:Exclude=[xunit.*]* /p:CollectCoverage=true "/p:CoverletOutputFormat=\"cobertura,opencover\""

- task: PublishCodeCoverageResults@1
  displayName: 'Publishing coverage results'
  continueOnError: true
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(sourceTestFolder)$(coberturaFileName)'

- task: CopyFiles@2
  continueOnError: true
  inputs:
    SourceFolder: '$(sourceTestFolder)'
    Contents: '$(openCoverFileName)'
    TargetFolder: '$(Build.SourcesDirectory)/TestResults/Coverage/'
    OverWrite: true
  displayName: 'copying coverage results'

- task: CopyFiles@2
  continueOnError: true
  inputs:
    SourceFolder: '$(sourceTestFolder)'
    Contents: '*.trx'
    TargetFolder: '$(Build.SourcesDirectory)/TestResults/Report/'
    OverWrite: true
  displayName: 'copying tests report'  

# - task: SonarCloudAnalyze@1
#   displayName: Runing SonarCloudAnalyze

# - task: SonarCloudPublish@1
#   displayName: Pushing SonarCloudAnalyze
#   inputs:
#     pollingTimeoutSec: '300'