# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  sourcePath: 'src/MeerkatUpdater'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'

- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: runtime 

- script: dotnet build --configuration $(buildConfiguration)
  continueOnError: false
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: $(sourcePath)
