name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  baseProjectPath: ../../src/MeerkatUpdater/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build Configurations
      run: dotnet build $baseProjectPath/MeerkatUpdater.Config --configuration Release
    - name: Build Core
      run: dotnet build $baseProjectPath/MeerkatUpdater.Core --configuration Release
    - name: Test Configs
      run: dotnet test $baseProjectPath/MeerkatUpdater.Config.Test --no-build
    - name: Test Core
      run: dotnet test $baseProjectPath/MeerkatUpdater.Core.Test --no-build      
